name: hello world
on:
  push:
    branches:
      - main
jobs:
  say-hello:
    runs-on: windows-latest
    steps:
      - name: Say Hello
      - run: echo "TODAY =$(date+ %y-%m-%d)" >> $GITHUB_ENV
      - run: echo HelloWorld, Today is $TODAY
