name: hello world
on:
  push:
    paths:
      - '!README.md'
      - '!docs/**'
      - '**.js'
      - '**.html'
    branches:
      - main
      - release/**
      - '!develop/**'
jobs:
  say-hello:
    runs-on: windows-latest
    steps:
      - name: Say Hello
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Display Message
        run: echo "Hello World, Today is $NOW"