name: hello world
on:
  push:
    branches:
      - main
jobs:
  say-hello:
    runs-on: windows-latest
    steps:
      - name: Say Hello
        run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - name: Display Message
        run: echo "Hello World, Today is $TODAY"